src/Entity/Partida.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PartidaRepository")
 */
class Partida
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column (type="text")
     */
    private $descricao;

    /**
     * @var integer
     * @ORM\Column(type="integer")
     */
    private $placar_visitante;

    /**
     * @var integer
     * @ORM\Column (type = "integer")
     */

    private $placar_casa;

    /**
     * @var \DateTime
     * @ORM\Column (type = "datetime")
     */

    private $data_partida;


    /**
     * @var Campeonato
     * @ORM\ManyToOne(targetEntity="App\Entity\Campeonato")
     */
    private $campeonato;

    /**
     * @var Time
     * @ORM\ManyToOne(targetEntity="App\Entity\Time", inversedBy="partidas_casa")
     */
    private $time_casa;

    /**
     * @var Time
     * @ORM\ManyToOne(targetEntity="App\Entity\Time", inversedBy="partidas_visitante")
     */
    private $time_visitante;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     * @return Partida
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescricao()
    {
        return $this->descricao;
    }

    /**
     * @param string $descricao
     * @return Partida
     */
    public function setDescricao($descricao)
    {
        $this->descricao = $descricao;
        return $this;
    }

    /**
     * @return int
     */
    public function getPlacarVisitante()
    {
        return $this->placar_visitante;
    }

    /**
     * @param int $placar_visitante
     * @return Partida
     */
    public function setPlacarVisitante($placar_visitante)
    {
        $this->placar_visitante = $placar_visitante;
        return $this;
    }

    /**
     * @return int
     */
    public function getPlacarCasa()
    {
        return $this->placar_casa;
    }

    /**
     * @param int $placar_casa
     * @return Partida
     */
    public function setPlacarCasa($placar_casa)
    {
        $this->placar_casa = $placar_casa;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDataPartida()
    {
        return $this->data_partida;
    }

    /**
     * @param \DateTime $data_partida
     * @return Partida
     */
    public function setDataPartida($data_partida)
    {
        $this->data_partida = $data_partida;
        return $this;
    }

    /**
     * @return Campeonato
     */
    public function getCampeonato()
    {
        return $this->campeonato;
    }

    /**
     * @param Campeonato $campeonato
     * @return Partida
     */
    public function setCampeonato($campeonato)
    {
        $this->campeonato = $campeonato;
        return $this;
    }

    /**
     * @return Time
     */
    public function getTimeCasa()
    {
        return $this->time_casa;
    }

    /**
     * @param Time $time_casa
     * @return Partida
     */
    public function setTimeCasa($time_casa)
    {
        $this->time_casa = $time_casa;
        return $this;
    }

    /**
     * @return Time
     */
    public function getTimeVisitante()
    {
        return $this->time_visitante;
    }

    /**
     * @param Time $time_visitante
     * @return Partida
     */
    public function setTimeVisitante($time_visitante)
    {
        $this->time_visitante = $time_visitante;
        return $this;
    }
}

src/Controller/PartidaController.php
<?php

namespace App\Controller;

use App\Entity\Partida;
use App\Entity\Time;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\VarDumper\VarDumper;

class PartidaController extends Controller
{
    protected $em;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->em = $entityManager;
    }

    /**
     * @Route("/partida", name="partida")
     */
    public function index()
    {
        return $this->render('partida/index.html.twig', [
            'controller_name' => 'PartidaController',
        ]);
    }

    /**
     * @param Time $time
     * @Route ("/partida/listar-por-time/{id}", name="listar_partidas")
     * @Template ("partida/listar-por-time.html.twig")
     * @return array
     */

    public function partidasPorTimes(Time $time)
    {
        $partidas = $this->em->getRepository(Partida::class)->getPartidasPorTime($time);

        VarDumper::dump($partidas);
        return [
            'partidas' => $partidas,
            'time' => $time
        ];

    }

}

templates/partida/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'src/Controller/PartidaController.php'|file_link(0) }}">src/Controller/PartidaController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'templates/partida/index.html.twig'|file_link(0) }}">templates/partida/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/partida/listar-por-time.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1 class="display-3">Partidas de "{{ time.nome }}"</h1>

    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Campeonato</th>
            <th>Adversário</th>
            <th>Placar</th>
            <th>Local</th>
            <th>Data</th>
        </tr>
        </thead>
        <tbody>
        {% for partida in partidas %}
            <tr>
                <td>{{ partida.campeonato.nome }}</td>
                <td>
                    {% if time.id == partida.timeCasa.id %}
                        {{ partida.timeVisitante.nome }}
                    {% else %}
                        {{ partida.timeCasa.nome }}
                    {% endif %}
                </td>
                <td>

                    {% if time.id == partida.timeCasa.id %}
                        {{ partida.placarCasa }} x {{ partida.placarVisitante }}
                    {% else %}
                        {{ partida.placarVisitante }} x {{ partida.placarCasa }}
                    {% endif %}

                </td>
                <td>

                    {% if time.id == partida.timeCasa.id %}
                        Time da casa
                    {% else %}
                        Time Visitante
                    {% endif %}

                </td>
                <td>{{ partida.dataPartida|date("d/m/Y H:i") }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

{% block title %}
    Listando partidas de "{{ time.nome }}" -
{% endblock %}